name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.5
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  animations: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
